# Generated by Django 2.1.7 on 2019-03-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0002_document_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='userid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
